### ISSUE TITLE
找不到标签？？

### ISSUE THREAD

**Issue by hongyang20** [jarjune/vue-number-scroll#2]
![image](https://user-images.githubusercontent.com/43112151/82042550-a39a6e80-96dc-11ea-9d8e-f91faa4bbc62.png)

**Comment by jarjune** [comment]
components没引入吧

**Comment by hongyang20** [comment]
![image](https://user-images.githubusercontent.com/43112151/82055179-b455df00-96f2-11ea-9d5b-c68414cac64d.png) 引入了，也能console.log(vns)对象，可还是报标签找不到，求指教
@jarjune

**Comment by jarjune** [comment]
![image](https://user-images.githubusercontent.com/19874732/82056073-f9c6dc00-96f3-11ea-97c4-558a5e660c26.png)

**Comment by hongyang20** [comment]
谢谢大佬

**Comment by hongyang20** [comment]
大佬，可以用js触发吗，现在还没翻到这页他就在跑了 @jarjune

**Comment by jarjune** [comment]
那就start和end都为0，你翻到这页的时候 把end改掉

**Comment by hongyang20** [comment]
大佬威武
