### ISSUE TITLE
老板这个 怎么 设置滚动啊~~~：219,723,654

### ISSUE THREAD

**Issue by darkerli** [jarjune/vue-number-scroll#3]
滚动啊~~~：219,723,654 怎么才能有 逗号 分隔符

**Comment by jarjune** [comment]
参考例子：[https://github.com/jarjune/vue-number-scroll/blob/master/example/index.html](https://github.com/jarjune/vue-number-scroll/blob/master/example/index.html)

**Comment by darkerli** [comment]
谢谢 我后面 也想到了 是设置 format ， 还是非常感谢你 蛤蛤
